version: '3'

services:
  django-backend:
    container_name: backend 
    restart : always 
    build:
      context: ./server
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis 
    volumes:
      - ./server:/app

    env_file:
      - .env.server 
    networks:
      - jio

  chess-frontend:
    container_name: frontend
    restart : always 
    build:
      context: ./chess-front
      target: development  
    ports:
      - "5173:5173"
    volumes:
      - ./chess-front:/app
      - exclude:/app/node_modules/

    depends_on:
      - django-backend
    # command: sh -c "/usr/src/app/update_env.sh && npm run dev"
    networks:
      - jio

  postgres:
    container_name: db 
    restart : always 
    build :  
      context : ./db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jio
  redis :
    container_name: redis 
    image: redis:latest
    restart : always 
    ports:
      - "6379:6379"
    # volumes:
    #   - ./redis.conf:/etc/redis/redis.conf
    # command: ["redis-server", "/etc/redis/redis.conf"]
    networks:
      - jio

volumes:
  postgres_data:
  exclude:

networks:
  jio:
    driver: bridge


  
