version: '3'

services:
  django-backend:
    container_name: backend 
    build:
      context: ./server
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./server:/app

  chess-frontend:
    container_name: frontend
    build:
      context: ./chess-front
      target: development  
    ports:
      - "5173:5173"
    volumes:
      - ./chess-front:/usr/src/app

  postgres:
    container_name: db 
    image: postgres:latest
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: komal
      POSTGRES_PASSWORD: komal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
