# Generated by Django 4.2.6 on 2023-10-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('channel_name_1', models.CharField(max_length=255, unique=True)),
                ('channel_name_2', models.CharField(max_length=255, null=True, unique=True)),
                ('gameid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
