# Generated by Django 4.2.6 on 2023-11-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socket_config', '0003_customgame'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomGame',
        ),
    ]
