# Generated by Django 4.2.6 on 2023-11-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socket_config', '0004_delete_customgame'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGame',
            fields=[
                ('game_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('creator', models.CharField(max_length=255, unique=True)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
